
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jonp-charts
  namespace: apps
spec:
  chart:
    spec:
      version: ">=0.1.0"
  values:
    image:
      repository: ghcr.io/jonpjenkins/gowebserver
      tag: staging-1afa1a24-1622124356
    service:
      port: 8080