
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gowebserver
  namespace: apps
spec:
  chart:
    spec:
      version: ">=0.1.0"
  values:
    image:
      repository: ghcr.io/jonpjenkins/gowebserver
      tag: staging-4f68ec8a-1622596372
    service:
      port: 8080