apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jonp-charts
  namespace: flux-system
spec:
  interval: 30s
  url: https://raw.githubusercontent.com/jonpjenkins/helm-chart/main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jonp-charts
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart-demo
      sourceRef:
        kind: HelmRepository
        name: jonp-charts
      version: '>=0.1.0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: gowebserver
  targetNamespace: staging
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: ghcr.io/jonpjenkins/gowebserver
      tag: staging-1afa1a24-1622124356
    service:
      port: 8080
