apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gowebserver
  namespace: apps
spec:
  interval: 30s
  url: https://raw.githubusercontent.com/jonpjenkins/helm-chart/main