apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gowebserver
  namespace: apps
spec:
  serviceAccountName: dev-team
  releaseName: gowebserver
  chart:
    spec:
      chart: helm-chart-demo
      sourceRef:
        kind: HelmRepository
        name: gowebserver
      version: '>=0.1.0'
  interval: 10s